config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :friends, only: [:create, :destroy], path: 'users/:user_id/friends'

  get 'api/news', to: 'tweets#api_news'
  get 'api/:fecha1/:fecha2', to: 'tweets#api_dates'
  post 'api/create_tweet/:content', to: 'tweets#api_create'

  root to: redirect("tweets")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates  :content,      presence:    true
  has_many   :likes,        dependent:   :destroy
  belongs_to :retweet_from, class_name:  "Tweet",           optional:  true, counter_cache: true
  has_many   :tweets,       foreign_key: "retweet_from_id", dependent: :destroy
  
  scope :include_all,   -> { includes(:tweets, user: :friends, retweet_from: [:user, :likes, :tweets]) }
  scope :desc,          -> { order(id: :desc) }
  scope :tweets_for_me, -> (friends_list) { where(user_id: (friends_list.map { |friend| friend.friend_id } << friends_list[0].user_id)) }
  scope :page,          -> (page) { offset(50 * (page - 1)).limit(50) }
  scope :search_for,    -> (search) { where("lower(content) LIKE ?", "%#{search}%".downcase) }
  scope :between_dates, -> (date1, date2) { where(created_at: date1.beginning_of_day..date2.end_of_day) }

  def split_content
    self.content.split(" ")
  end
  
  def get_hashtags
    self.split_content.select { |word| word.match(/\A#[a-zA-Z0-9]+\z/) }
  end
  
  def get_user_id
    self.user.id
  end
  
  def get_like_id(user)
    self.likes.find_by(user_id: user.id)
  end
  
  def liked_by?(user)
    self.likes.each do |like|
      return true if like.user == user
    end
    return false
  end

  def retweeted_by?(user)
    self.tweets.each do |tweet|
      return true if tweet.user == user
    end
    return false
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :api_news, :api_dates]
  before_action :set_tweet,          only: [:show, :edit, :update, :destroy]
  before_action :set_page,           only: [:index]
  before_action :find_reference,     only: [:new, :create]
  before_action :new_friend,         only: [:index, :show]
  
  protect_from_forgery with: :null_session

  # GET /tweets
  def index
    @tweet = Tweet.new
    if params[:search].present?
      @tweets = Tweet.search_for(params[:search]).include_all.desc.page(@page)
    elsif user_signed_in?
      unless current_user.friends.empty?
        @tweets = Tweet.tweets_for_me(current_user.friends).include_all.desc.page(@page)
      else
        @tweets = current_user.tweets.include_all.desc.page(@page)
      end
    else
      @tweets = Tweet.include_all.desc.page(@page)
    end
  end

  # GET /tweets/1
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    redirect_to tweets_path, notice: "Oops! You're not supposed to do that." unless @tweet.user_id == current_user.id
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.retweet_from_id = @reference.id unless @reference.nil?

    if @tweet.save
      redirect_to root_path, notice: 'Your tweet was successfully created.'
    else
      redirect_to tweets_url, notice: 'Your tweet must have content.'
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Your tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: 'Your tweet was successfully destroyed.'
  end

  # API methods
  # GET /api/news
  def api_news
    @tweets = Tweet.desc.limit(50)

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Oops! You shouldn't be doing that." }
      format.json { render :api_news }
    end
  end

  # GET /api/:fecha1/:fecha2
  def api_dates
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Oops! You shouldn't be doing that." }
      begin
        date1 = Date.parse(params[:fecha1])
        date2 = Date.parse(params[:fecha2])
        @tweets = Tweet.between_dates(date1, date2).desc
        format.json { render :api_dates }
      rescue ArgumentError
        format.json { render json: "Invalid dates." }
      end
    end
  end

  # GET /api/create_tweet/:content
  def api_create
    @tweet = Tweet.new(user_id: current_user.id, content: params[:content])

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Oops! You shouldn't be doing that." }
      if @tweet.save
        format.json { render :show, status: :created, location: @tweet }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content, :retweet_from_id)
    end

    def set_page
      @page = params[:page].nil? ? 1 : params[:page].to_i
    end

    def find_reference
      @reference = Tweet.find(params[:reference]) unless params[:reference].nil?
    end

    def new_friend
      @friend = Friend.new
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card w-100">
  <div class="d-flex">

    <img src="<%= resource.user.profile_pic_url %>" style="width: 50px; height: 50px;" class="rounded-circle ml-3 mt-3" alt="profile pic">
        
    <div class="card-body p-3">
      
      <div class="d-flex align-items-center justify-content-between">
              
        <div class="d-flex">
          <h5 class="card-title font-weight-bold"><%= resource.user %></h5>
          <span><%= link_to "#{time_ago_in_words(resource.created_at)} ago", resource, class: "text-muted ml-2" %></span>
        </div>
              
        <% if user_signed_in? %>

          <% if resource.get_user_id == current_user.id %>
            
            <div>
              <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                <div class="dropdown-menu">
                  <%= link_to fa_icon("pencil") + " Edit tweet", edit_tweet_path(resource), class: "dropdown-item" %>
                  <%= link_to fa_icon("trash-o") + " Delete tweet", tweet_path(resource),
                      class: "dropdown-item",
                      data: { confirm: "Are you sure?" },
                      method: :delete %>
                </div>
            </div>

          <% else %>

            <% unless current_user.follows?(resource.user) %>

              <%= form_with(model: @friend, url: friends_path(current_user.id)) do |f| %>
                <%= f.hidden_field :friend_id, value: resource.get_user_id %>
                <%= f.submit "Follow", class: "btn btn-outline-info rounded-pill" %>
              <% end %>
              
            <% else %>
            
              <%= link_to "Unfollow",
                  friend_path(current_user.id,
                  current_user.get_follow_id(resource.user)),
                  class: "btn btn-outline-info rounded-pill", method: "delete" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <p class="card-text mb-1">
        <% resource.split_content.each do |word| %>
          <% if resource.get_hashtags.include?(word) %>
            <%= link_to word, tweets_path(search: word) %>
          <% else %>
            <%= "#{word} " %>
          <% end %>
        <% end %>
      </p>

      <% unless resource.retweet_from_id.nil? %>
        <%= render 'tweet', resource: resource.retweet_from %>
      <% end %>

      <div class="d-flex justify-content-around">

        <div>
          <%= link_to fa_icon("retweet"),
              new_tweet_path({ reference: resource }),
              class: "#{resource.retweeted_by?(current_user) ? "text-success" : "text-muted"}" %>
          <span class="text-muted ml-3"><%= resource.tweets_count %></span>
        </div>

        <div>
          <% if user_signed_in? && resource.liked_by?(current_user) %>
            <%= link_to fa_icon("heart"), tweet_like_path(resource, resource.get_like_id(current_user)), method: "delete", class: "text-danger" %>
          <% else %>
            <%= link_to fa_icon("heart-o"), tweet_likes_path(resource), method: "post", class: "text-muted" %>
          <% end %>
          <span class="text-muted ml-3"><%= resource.likes_count %></span>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'tweets/forms/new_form', tweet: @tweet %>

<%= link_to 'Back', :back %>

app/views/tweets/index.html.erb
<% content_for :title, "Home" %>

<div class="d-flex flex-column h-100">

  <nav class="navbar navbar-light bg-light border">
    <a class="navbar-brand font-weight-bold">Twitter</a>

    <%= form_tag(tweets_path, method: "get") do %>
      <%= fa_icon("search") %>
      <%= text_field_tag :search, nil, placeholder: "Search Twitter", class: "from-control mr-sm-2 rounded-pill border px-3 py-1" %>
    <% end %>
    
  </nav>

  <div class="overflow-auto">

    <%= render 'tweets/forms/new_form', tweet: @tweet, class: "form-group" if user_signed_in? %>

    <% @tweets.each do |tweet| %>
      <%= render 'tweet', resource: tweet %>
    <% end %>

    <br>

    <div class="d-flex flex-column text-center align-items-middle">
      <%= link_to 'Show more tweets', tweets_path(page: @page + 1), class: "font-weight-bold h3" unless @tweets.length < 50 %>
      <%= link_to 'Previous page', tweets_path(page: @page - 1), class: "font-weight-bold" unless @page == 1 %>
    </div>

  </div>

</div>

app/views/tweets/new.html.erb
<h1>Retweet</h1>

<%= render 'tweets/forms/new_form', tweet: @tweet %>

app/views/tweets/show.html.erb
<%= render 'tweet', resource: @tweet %>

<% unless @tweet.likes.length == 0 %>
  
  <div style="display: flex;">
    
    <% @tweet.likes.each do |like| %>

      <figure class="text-center mx-3 my-3">
        <img src="<%= like.user_pic_url %>" style="width: 50px; height: 50px;" class="rounded-circle" alt="profile pic">
        <figcaption><%= like.user %> liked this tweet</figcaption>
      </figure>

    <% end %>
  
  </div>

<% else %>
  <p>This tweet hasn't been liked yet.</p>
<% end %>