config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :friends, only: [:create, :destroy], path: 'users/:user_id/friends'

  get 'api/news', to: 'tweets#api_news'
  get 'api/:fecha1/:fecha2', to: 'tweets#api_dates'
  post 'api/create_tweet/:content', to: 'tweets#api_create'

  root to: redirect("tweets")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> / Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">


    <div class="row">

      <div class="col-3 col-lg-2 border-right px-3 position-fixed">
        <div class="d-flex flex-column">
          <%= link_to fa_icon("twitter"), tweets_path, class: "text-primary fa-4x ml-3" %>
          <div class="mt-2 d-flex flex-column">
            
            <%= link_to(tweets_path) do %>
              <div class="d-flex align-items-center justify-content-center mt-4 text-body">
                <div class="w-50 text-center"><%= fa_icon("home", class: "fa-3x") %></div>
                <h4 class="w-50 font-weight-bold d-none d-lg-block">Home</h4>
              </div>
            <% end %>
            
            <% if user_signed_in? %>

              <%= link_to(destroy_user_session_path, method: "delete") do %>
                <div class="d-flex align-items-center justify-content-center mt-4 text-body">
                  <div class="w-50 text-center"><%= fa_icon("sign-out", class: "fa-3x") %></div>
                  <h4 class="w-50 font-weight-bold d-none d-lg-block">Log out</h4>
                </div>
              <% end %>

            <% else %>

              <% unless current_page?(new_user_session_path) %>
                <%= link_to(new_user_session_path) do %>
                  <div class="d-flex align-items-center justify-content-center mt-4 text-body">
                    <div class="w-50 text-center"><%= fa_icon("sign-in", class: "fa-3x") %></div>
                    <h4 class="w-50 font-weight-bold d-none d-lg-block">Log in</h4>
                  </div>
                <% end %>
              <% end %>

              <% unless current_page?(new_user_registration_path) %>
                <%= link_to(new_user_registration_path) do %>
                  <div class="d-flex align-items-center justify-content-center mt-4 text-body">
                    <div class="w-50 text-center"><%= fa_icon("user-plus", class: "fa-3x") %></div>
                    <h4 class="w-50 font-weight-bold d-none d-lg-block">Sign up</h4>
                  </div>
                <% end %>
              <% end %>
            
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-9 offset-3 col-lg-10 offset-lg-2 vh-100 p-0">
        <% flash.each do |key, value| %>
          <p class="alert alert-secondary fixed top" role="alert"><%= value %></p>
        <% end %>
        <%= yield %>
      </div>

    </div>
  </body>
</html>